"""
Real PostgreSQL Alembic migration tests.

Every test in this file that needs a live database creates and drops its
OWN disposable PostgreSQL database (never touching a shared/dev database),
and invokes the REAL `alembic` CLI as a subprocess (not the Python API
in-process) -- this exercises exactly the same code path
(`alembic/env.py` reading `DATABASE_URL` fresh) that a real deployment
would use, rather than relying on any already-imported, possibly-stale
`app.database` module state in this test process.

HOW TO ACTUALLY RUN THESE TESTS:
    1. Start a real Postgres+PostGIS instance, e.g. via the repo's existing
       docker-compose service:
           docker-compose up -d db
    2. Point TEST_DATABASE_URL at it (only used to derive the admin
       connection + disposable database names -- no tables are ever
       created directly in the database this URL names):
           export TEST_DATABASE_URL="postgresql+psycopg://postgres:postgres_password@localhost:5432/postgres"
    3. Run:
           pytest -m postgres_migration tests/test_migrations_postgres.py -v

Without TEST_DATABASE_URL pointing to a reachable PostgreSQL server, every
test in this file SKIPS (not fails, not fakes a pass).
"""
import os
import subprocess
import uuid as uuid_module
import ast
import glob

import pytest
from sqlalchemy import create_engine, text, inspect
from sqlalchemy.engine import make_url

pytestmark = pytest.mark.postgres_migration

_TEST_DATABASE_URL = os.getenv("TEST_DATABASE_URL") or os.getenv("POSTGRES_TEST_DATABASE_URL")
_BACKEND_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Known PostGIS TIGER-geocoder/topology system table names -- must NEVER
# be created/managed by this application's migrations (see the
# migration-history repair phase report for how they ended up in the
# original autogenerated migration by mistake).
_TIGER_TABLE_NAMES = {
    "zip_lookup_all", "pagc_lex", "loader_platform", "featnames", "zip_state",
    "faces", "zcta5", "loader_variables", "topology", "bg", "pagc_gaz",
    "loader_lookuptables", "direction_lookup", "zip_state_loc", "pagc_rules",
    "street_type_lookup", "state", "place", "tract", "geocode_settings",
    "state_lookup", "zip_lookup_base", "zip_lookup", "place_lookup",
    "tabblock20", "tabblock", "addr", "county_lookup", "layer",
    "secondary_unit_lookup", "geocode_settings_default", "cousub", "edges",
    "addrfeat", "county", "countysub_lookup",
}

_APP_TABLE_NAMES = {
    "users", "police_stations", "constables", "constable_locations",
    "incidents", "incident_assignments", "evidence", "audit_logs",
    "devices", "battery_readings", "alerts",
    "recording_sessions", "video_chunks", "remote_commands",
}


def _postgres_reachable() -> bool:
    if not _TEST_DATABASE_URL:
        return False
    try:
        engine = create_engine(_TEST_DATABASE_URL)
        conn = engine.connect()
        conn.close()
        engine.dispose()
        return True
    except Exception:
        return False


_PG_AVAILABLE = _postgres_reachable()
_SKIP_REASON = (
    "No reachable PostgreSQL instance configured for migration integration "
    "testing. Set TEST_DATABASE_URL (see this file's module docstring for "
    "exact setup steps) to actually run this test. NOT executed in the "
    "current environment -- this is a skip, not a pass."
)


def _run_alembic(args, database_url):
    env = dict(os.environ)
    env["DATABASE_URL"] = database_url
    env.setdefault("JWT_SECRET_KEY", "test-secret-for-migration-tests")
    result = subprocess.run(
        ["alembic"] + args,
        cwd=_BACKEND_DIR,
        env=env,
        capture_output=True,
        text=True,
        timeout=120,
    )
    return result


@pytest.fixture()
def disposable_database():
    """
    Creates a brand-new, completely empty PostgreSQL database (via the
    admin/maintenance connection derived from TEST_DATABASE_URL) and yields
    its own connection URL. Dropped unconditionally in teardown, regardless
    of test outcome -- never leaves disposable test databases lying around.
    """
    base_url = make_url(_TEST_DATABASE_URL)
    admin_url = base_url.set(database="postgres")
    db_name = f"sp_migtest_{uuid_module.uuid4().hex[:12]}"
    admin_engine = create_engine(admin_url, isolation_level="AUTOCOMMIT")
    with admin_engine.connect() as conn:
        conn.execute(text(f'CREATE DATABASE "{db_name}"'))

    test_url = base_url.set(database=db_name).render_as_string(hide_password=False)
    try:
        yield test_url
    finally:
        with admin_engine.connect() as conn:
            conn.execute(text(
                "SELECT pg_terminate_backend(pid) FROM pg_stat_activity "
                "WHERE datname = :name AND pid <> pg_backend_pid()"
            ), {"name": db_name})
            conn.execute(text(f'DROP DATABASE IF EXISTS "{db_name}"'))
        admin_engine.dispose()


# ---------------------------------------------------------------------------
# 1. Fresh database upgrade
# ---------------------------------------------------------------------------
@pytest.mark.skipif(not _PG_AVAILABLE, reason=_SKIP_REASON)
def test_fresh_database_upgrade_succeeds(disposable_database):
    result = _run_alembic(["upgrade", "head"], disposable_database)
    assert result.returncode == 0, f"alembic upgrade head failed:\nSTDOUT:\n{result.stdout}\nSTDERR:\n{result.stderr}"

    current = _run_alembic(["current"], disposable_database)
    assert current.returncode == 0
    assert "6b1f4a9d3e72" in current.stdout or "6b1f4a9d3e72" in current.stderr


# ---------------------------------------------------------------------------
# 2. Second upgrade is a no-op
# ---------------------------------------------------------------------------
@pytest.mark.skipif(not _PG_AVAILABLE, reason=_SKIP_REASON)
def test_second_upgrade_is_noop(disposable_database):
    first = _run_alembic(["upgrade", "head"], disposable_database)
    assert first.returncode == 0

    second = _run_alembic(["upgrade", "head"], disposable_database)
    assert second.returncode == 0
    assert "Running upgrade" not in second.stdout
    assert "Running upgrade" not in second.stderr


# ---------------------------------------------------------------------------
# 3. Expected application tables exist / no PostGIS TIGER system tables
# ---------------------------------------------------------------------------
@pytest.mark.skipif(not _PG_AVAILABLE, reason=_SKIP_REASON)
def test_expected_application_tables_exist_and_no_tiger_tables(disposable_database):
    result = _run_alembic(["upgrade", "head"], disposable_database)
    assert result.returncode == 0

    engine = create_engine(disposable_database)
    try:
        table_names = set(inspect(engine).get_table_names())
    finally:
        engine.dispose()

    missing = _APP_TABLE_NAMES - table_names
    assert not missing, f"Missing expected application tables: {missing}"

    tiger_present = _TIGER_TABLE_NAMES & table_names
    assert not tiger_present, f"PostGIS TIGER/topology tables are being managed by Alembic: {tiger_present}"


# ---------------------------------------------------------------------------
# 4. PostGIS extension exists
# ---------------------------------------------------------------------------
@pytest.mark.skipif(not _PG_AVAILABLE, reason=_SKIP_REASON)
def test_postgis_extension_exists_after_upgrade(disposable_database):
    result = _run_alembic(["upgrade", "head"], disposable_database)
    assert result.returncode == 0

    engine = create_engine(disposable_database)
    try:
        with engine.connect() as conn:
            row = conn.execute(text("SELECT extname FROM pg_extension WHERE extname = 'postgis'")).fetchone()
        assert row is not None, "postgis extension was not created by the migration"
    finally:
        engine.dispose()


# ---------------------------------------------------------------------------
# 5. (covered by test 3 above -- kept as an explicit, separately-named test
#    per the requested checklist item, asserting the same property from a
#    different angle: absence of TIGER-specific enum/system objects)
# ---------------------------------------------------------------------------
@pytest.mark.skipif(not _PG_AVAILABLE, reason=_SKIP_REASON)
def test_no_tiger_geocoder_extension_was_enabled_by_our_migrations(disposable_database):
    """
    Our migrations only ever enable bare `postgis` -- never
    `postgis_tiger_geocoder`/`postgis_topology`. This directly tests that
    property, distinct from test 3's table-name check.
    """
    result = _run_alembic(["upgrade", "head"], disposable_database)
    assert result.returncode == 0

    engine = create_engine(disposable_database)
    try:
        with engine.connect() as conn:
            rows = conn.execute(text(
                "SELECT extname FROM pg_extension WHERE extname IN ('postgis_tiger_geocoder', 'postgis_topology')"
            )).fetchall()
        assert rows == [], f"Unexpected extension(s) enabled by our migration chain: {rows}"
    finally:
        engine.dispose()


# ---------------------------------------------------------------------------
# 6. Evidence verification schema exists
# ---------------------------------------------------------------------------
@pytest.mark.skipif(not _PG_AVAILABLE, reason=_SKIP_REASON)
def test_evidence_verification_schema_exists(disposable_database):
    result = _run_alembic(["upgrade", "head"], disposable_database)
    assert result.returncode == 0

    engine = create_engine(disposable_database)
    try:
        columns = {c["name"] for c in inspect(engine).get_columns("evidence")}
    finally:
        engine.dispose()

    expected = {
        "verified_by", "verified_at", "rejected_by", "rejected_at",
        "rejection_reason", "archived_by", "archived_at",
        "comment", "storage_key", "upload_status", "uploader_id", "uploader_role",
    }
    missing = expected - columns
    assert not missing, f"Missing expected evidence columns: {missing}"


# ---------------------------------------------------------------------------
# 7. Active-assignment partial unique index exists
# ---------------------------------------------------------------------------
@pytest.mark.skipif(not _PG_AVAILABLE, reason=_SKIP_REASON)
def test_active_assignment_partial_unique_index_exists(disposable_database):
    result = _run_alembic(["upgrade", "head"], disposable_database)
    assert result.returncode == 0

    engine = create_engine(disposable_database)
    try:
        with engine.connect() as conn:
            row = conn.execute(text(
                "SELECT indexdef FROM pg_indexes WHERE indexname = 'uq_active_assignment_per_incident'"
            )).fetchone()
        assert row is not None, "uq_active_assignment_per_incident index does not exist"
        indexdef = row[0]
        assert "UNIQUE" in indexdef
        assert "WHERE" in indexdef  # confirms it's a genuine partial index, not a plain unique index
    finally:
        engine.dispose()


# ---------------------------------------------------------------------------
# 8. Geometry columns exist with the expected type/SRID
# ---------------------------------------------------------------------------
@pytest.mark.skipif(not _PG_AVAILABLE, reason=_SKIP_REASON)
def test_geometry_columns_have_expected_type_and_srid(disposable_database):
    result = _run_alembic(["upgrade", "head"], disposable_database)
    assert result.returncode == 0

    engine = create_engine(disposable_database)
    try:
        with engine.connect() as conn:
            rows = conn.execute(text(
                "SELECT f_table_name, f_geometry_column, type, srid FROM geometry_columns "
                "WHERE f_table_name IN ('incidents', 'evidence', 'constable_locations', 'police_stations') "
                "ORDER BY f_table_name, f_geometry_column"
            )).fetchall()
    finally:
        engine.dispose()

    found = {(r[0], r[1]): (r[2], r[3]) for r in rows}
    assert found.get(("incidents", "location")) == ("POINT", 4326)
    assert found.get(("evidence", "location")) == ("POINT", 4326)
    assert found.get(("constable_locations", "location")) == ("POINT", 4326)
    assert found.get(("police_stations", "location")) == ("POINT", 4326)
    assert found.get(("police_stations", "jurisdiction")) == ("POLYGON", 4326)


# ---------------------------------------------------------------------------
# 9. Existing evidence survives an upgrade
# ---------------------------------------------------------------------------
@pytest.mark.skipif(not _PG_AVAILABLE, reason=_SKIP_REASON)
def test_existing_evidence_survives_upgrade(disposable_database):
    """
    Brings a database to an OLDER revision (before the two schema-drift
    corrective migrations), inserts a real Incident + Evidence row using
    only the columns that exist at that revision, then upgrades the rest
    of the way to head, and confirms that row is completely unchanged.
    """
    older_head = "6c1a9f3e7b52"  # last revision before the display_id/comment fixes
    older_result = _run_alembic(["upgrade", older_head], disposable_database)
    assert older_result.returncode == 0

    engine = create_engine(disposable_database)
    incident_id = str(uuid_module.uuid4())
    evidence_id = str(uuid_module.uuid4())
    try:
        with engine.begin() as conn:
            conn.execute(text(
                "INSERT INTO incidents (id, location, status) VALUES "
                "(:id, ST_GeomFromEWKT('POINT(5 5)'), 'new')"
            ), {"id": incident_id})
            conn.execute(text(
                "INSERT INTO evidence (id, incident_id, type, upload_status, file_hash) VALUES "
                "(:eid, :iid, 'photo', 'uploaded', :hash)"
            ), {"eid": evidence_id, "iid": incident_id, "hash": "pre-upgrade-hash-12345"})
    finally:
        engine.dispose()

    final_result = _run_alembic(["upgrade", "head"], disposable_database)
    assert final_result.returncode == 0

    verify_engine = create_engine(disposable_database)
    try:
        with verify_engine.connect() as conn:
            row = conn.execute(text(
                "SELECT file_hash, upload_status, incident_id FROM evidence WHERE id = :eid"
            ), {"eid": evidence_id}).fetchone()
        assert row is not None, "Evidence row disappeared after upgrade"
        assert row[0] == "pre-upgrade-hash-12345"
        assert row[1] == "uploaded"
        assert str(row[2]) == incident_id
    finally:
        verify_engine.dispose()


# ---------------------------------------------------------------------------
# 10. Downgrade/upgrade cycle on a disposable database
# ---------------------------------------------------------------------------
@pytest.mark.skipif(not _PG_AVAILABLE, reason=_SKIP_REASON)
def test_downgrade_base_then_upgrade_head_cycle(disposable_database):
    up1 = _run_alembic(["upgrade", "head"], disposable_database)
    assert up1.returncode == 0

    down = _run_alembic(["downgrade", "base"], disposable_database)
    assert down.returncode == 0, f"downgrade base failed:\nSTDOUT:\n{down.stdout}\nSTDERR:\n{down.stderr}"

    engine = create_engine(disposable_database)
    try:
        table_names = set(inspect(engine).get_table_names())
        with engine.connect() as conn:
            enum_rows = conn.execute(text(
                "SELECT typname FROM pg_type WHERE typname IN "
                "('userrole','userstatus','constablestatus','incidentstatus','mediatype','uploadstatus','assignmentstatus')"
            )).fetchall()
    finally:
        engine.dispose()

    # Only alembic_version + PostGIS's own spatial_ref_sys should remain --
    # no application tables, and (critically) no orphaned enum types either
    # (see the phase report on why this bug specifically blocked re-upgrade).
    assert not (_APP_TABLE_NAMES & table_names), f"Application tables survived downgrade base: {_APP_TABLE_NAMES & table_names}"
    assert enum_rows == [], f"Orphaned enum types survived downgrade base: {enum_rows}"

    up2 = _run_alembic(["upgrade", "head"], disposable_database)
    assert up2.returncode == 0, f"re-upgrade after downgrade base failed:\nSTDOUT:\n{up2.stdout}\nSTDERR:\n{up2.stderr}"

    final_current = _run_alembic(["current"], disposable_database)
    assert "6b1f4a9d3e72" in final_current.stdout or "6b1f4a9d3e72" in final_current.stderr


# ---------------------------------------------------------------------------
# Extra: importing migration modules must not create database objects as a
# side effect (static check -- does NOT require a live database, so it runs
# unconditionally, unlike the tests above).
# ---------------------------------------------------------------------------
def test_migration_modules_have_no_top_level_op_calls():
    """
    Confirms, via AST inspection (not by importing and hoping nothing
    happens), that every `op.<method>(...)` call in every migration file is
    nested inside a `def upgrade()`/`def downgrade()` function body -- never
    at module level -- so merely importing a migration module (as Alembic
    itself does while building the revision graph, and as this very test
    file's collection does) can never execute DDL as a side effect.
    """
    migration_files = glob.glob(os.path.join(_BACKEND_DIR, "alembic", "versions", "*.py"))
    assert migration_files, "No migration files found -- check the glob path"

    for path in migration_files:
        with open(path) as f:
            tree = ast.parse(f.read(), filename=path)

        for node in ast.walk(tree):
            if isinstance(node, ast.Call):
                func = node.func
                is_op_call = (
                    isinstance(func, ast.Attribute)
                    and isinstance(func.value, ast.Name)
                    and func.value.id == "op"
                )
                if not is_op_call:
                    continue
                # Walk up from this Call node to confirm it's nested inside
                # a FunctionDef somewhere (not directly at module level).
                # ast doesn't give parent pointers by default, so re-walk
                # each top-level FunctionDef's own subtree and check
                # membership instead.
        # Simpler equivalent check: every op.* call found anywhere in the
        # module must be reachable by walking INTO some top-level FunctionDef
        # -- i.e. it must not appear when walking the module body with
        # FunctionDef subtrees excluded.
        function_bodies = set()
        for node in ast.walk(tree):
            if isinstance(node, ast.FunctionDef):
                for child in ast.walk(node):
                    function_bodies.add(id(child))

        for node in ast.walk(tree):
            if isinstance(node, ast.Call):
                func = node.func
                is_op_call = (
                    isinstance(func, ast.Attribute)
                    and isinstance(func.value, ast.Name)
                    and func.value.id == "op"
                )
                if is_op_call:
                    assert id(node) in function_bodies, (
                        f"{os.path.basename(path)} has an op.* call outside any function body "
                        f"(line {node.lineno}) -- this would execute at import time"
                    )
