"""Initial schema

Revision ID: 2f44e1be4993
Revises: 
Create Date: 2026-08-19 10:29:09.922157

NOTE (repaired -- see migration-history phase report):

This migration was originally auto-generated against a development
database provisioned via the `postgis/postgis:15-3.4` Docker image, which
(depending on build/init scripts) enables additional PostGIS extensions
(`postgis_tiger_geocoder`, `postgis_topology`) beyond bare `postgis` --
these install dozens of their OWN system tables (`faces`, `state`,
`place`, `edges`, `zcta5`, `topology`, `spatial_ref_sys`, etc.). Alembic's
autogenerate saw those extension-owned tables in the live database, saw
they weren't declared in `app/models.py`, and proposed DROPPING them in
`upgrade()` (with a matching recreation in `downgrade()` to reverse that
drop) -- exactly as autogenerate is supposed to behave when it thinks
something is a stray table that shouldn't exist. But these tables are
NOT stray application cruft: they belong to PostGIS extensions, are
managed by `CREATE EXTENSION`/`DROP EXTENSION`, and must never be
created, dropped, or otherwise owned by an application's own Alembic
migrations. Because of this, running the ORIGINAL version of this
migration against ANY fresh PostgreSQL+PostGIS database would either:
  - fail immediately (if the target database has bare `postgis` only --
    the DROP TABLE statements for tiger/topology tables error out because
    those tables were never created in the first place), or
  - silently destroy real PostGIS extension state (if the target database
    DOES have those extensions enabled).
This revision has been repaired to manage ONLY the application's own 8
tables. This is safe to do to an already-applied revision because Alembic
identifies a database's position in the migration chain purely by the
revision id recorded in `alembic_version` -- a database already stamped at
(or past) `2f44e1be4993` never re-executes this file's `upgrade()`/
`downgrade()` bodies again; only a database starting from scratch (i.e.
one that has, in practice, never successfully completed this migration
before, since the original version could not run to completion) is
affected by this repair. No revision id, no down_revision linkage, and no
later migration was changed.

A second, independent bug was also fixed here: the manually-scripted
`CREATE INDEX ... USING gist` statements for this application's OWN
Geometry columns (police_stations.location/jurisdiction, incidents.location,
constable_locations.location, evidence.location) duplicated indexes that
GeoAlchemy2 already creates automatically via its own DDL event listeners
whenever a `Geometry`-typed column's table is created (confirmed directly:
this is what produced the "relation ... already exists" error the very
first time this migration was actually executed against a real database).
Those five redundant manual index-creation statements have been removed;
GeoAlchemy2 still creates the identically-named indexes on its own.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = '2f44e1be4993'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Required for the Geometry columns created below. Idempotent -- safe
    # to run even if the target database (e.g. one provisioned via the
    # postgis/postgis Docker image) already has it enabled. This migration
    # deliberately does NOT enable postgis_tiger_geocoder/postgis_topology
    # -- the application has no use for them, and see the module docstring
    # above for what went wrong when a database that happened to have them
    # got autogenerated into this migration's history.
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")

    op.create_table('police_stations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('jurisdiction', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('contact', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # NOTE: no manual GIST index creation for `location`/`jurisdiction` here
    # -- GeoAlchemy2 creates `idx_police_stations_location` /
    # `idx_police_stations_jurisdiction` automatically (see module docstring).
    op.create_index(op.f('ix_police_stations_name'), 'police_stations', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('sso_id', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('admin', 'control_room', 'station', 'constable', 'citizen', name='userrole'), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='userstatus'), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sso_id')
    )
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('constables',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('badge_number', sa.String(), nullable=True),
    sa.Column('station_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('available', 'busy', 'offline', name='constablestatus'), nullable=True),
    sa.Column('battery_level', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['police_stations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('badge_number')
    )
    op.create_table('incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('citizen_id', sa.UUID(), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('new', 'verified', 'rejected', 'assigned', 'en_route', 'arrived', 'resolved', 'closed', 'needs_review', name='incidentstatus'), nullable=True),
    sa.Column('station_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['citizen_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['police_stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # NOTE: no manual GIST index for `location` -- see note above.
    op.create_table('constable_locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('constable_id', sa.UUID(), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['constable_id'], ['constables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # NOTE: no manual GIST index for `location` -- see note above.
    op.create_table('evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=True),
    sa.Column('constable_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Enum('photo', 'audio', 'video', name='mediatype'), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('file_hash', sa.String(), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['constable_id'], ['constables.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # NOTE: no manual GIST index for `location` -- see note above.
    op.create_table('incident_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=True),
    sa.Column('constable_id', sa.UUID(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['constable_id'], ['constables.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands (application tables only -- see module docstring) ###


def downgrade() -> None:
    # ### commands (application tables only -- see module docstring) ###
    # PostGIS extension objects (spatial_ref_sys, and -- if separately
    # enabled outside this migration -- postgis_topology/tiger_geocoder
    # tables) are intentionally left completely alone here. This migration
    # never created them, so it must not drop them, and `DROP EXTENSION
    # postgis` is deliberately NOT issued either: other schemas/extensions
    # in the same database may depend on it, and removing it is a
    # database-level administrative decision, not something an application
    # migration should do unilaterally.
    op.drop_table('incident_assignments')
    op.drop_table('evidence')
    op.drop_table('constable_locations')
    op.drop_table('incidents')
    op.drop_table('constables')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_police_stations_name'), table_name='police_stations')
    op.drop_table('police_stations')

    # SQLAlchemy auto-creates a PostgreSQL ENUM TYPE the first time a table
    # with an Enum-typed column is created (e.g. `CREATE TYPE userrole AS
    # ENUM (...)` happened implicitly above in upgrade(), NOT via an
    # explicit op.execute call). Dropping the TABLE does not drop the TYPE
    # -- confirmed directly: without these, a disposable-database
    # downgrade-then-reupgrade cycle failed with
    # `DuplicateObject: type "userrole" already exists` the moment
    # upgrade() tried to recreate the `users` table. Must run after every
    # table using these enums has already been dropped above.
    op.execute("DROP TYPE IF EXISTS userrole")
    op.execute("DROP TYPE IF EXISTS userstatus")
    op.execute("DROP TYPE IF EXISTS constablestatus")
    op.execute("DROP TYPE IF EXISTS incidentstatus")
    op.execute("DROP TYPE IF EXISTS mediatype")
    # ### end Alembic commands ###
