"""add missing evidence comment column

Revision ID: 3a9c5e1f8b06
Revises: 8e2f6a4c9d17
Create Date: 2026-08-22 00:00:01.000000

A second, independent schema-drift gap discovered via this phase's
mandatory fresh-database Alembic upgrade + comparison against
`Base.metadata` (see the migration-history repair phase report):
`Evidence.comment` has existed in `app/models.py` and been used by
`app/routers/media.py::upload_evidence` since the very first evidence
upload endpoint, but -- like `incidents.display_id` (see migration
8e2f6a4c9d17) -- it was never actually present in the original
autogenerated initial migration, so it was never added to any real
database that went through the Alembic chain rather than
`Base.metadata.create_all()`.

Nullable, purely additive; safe for any existing evidence rows.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '3a9c5e1f8b06'
down_revision: Union[str, None] = '8e2f6a4c9d17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column("evidence", sa.Column("comment", sa.String(), nullable=True))


def downgrade() -> None:
    op.drop_column("evidence", "comment")
